version: '2'
services:
    cloudflare-app:
        image: cloudflare
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cloudflare-mysql:3306/cloudflare?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cloudflare-mysql:
        extends:
            file: mysql.yml
            service: cloudflare-mysql
